### ISSUE TITLE
Can't regenerate all services with lake

### ISSUE THREAD

**Issue by duncan-bayne** [fukamachi/aws-sdk-lisp#1]
I'm trying to regenerate all AWS SDK services with lake:

```
CL-USER> (swank:set-default-directory "/usr/home/duncan/code/aws-sdk-lisp/")
"/usr/home/duncan/code/aws-sdk-lisp/"
CL-USER> (ql:quickload "lake")
To load "lake":
  Load 1 ASDF system:
    lake
; Loading "lake"
("lake")
CL-USER> (lake:lake)
```

This runs the default task, but that immediately produces the following error:

```
System "aws-sdk/generator" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]
```

Must I install the lake binary using Roswell and regenerate services that way?  Or is there a way of making this work from the REPL that I don't know?

**Comment by duncan-bayne** [comment]
This doesn't appear to be limited to using the REPL; if I install Roswell, and lake, I still see the error:

```
$ ros use sbcl-bin
$ lake            
Unhandled QUICKLISP-CLIENT:SYSTEM-NOT-FOUND:
  System "aws-sdk/generator" not found
```

**Comment by fukamachi** [comment]
The directory `aws-sdk-lisp` places must be included in ASDF's source registry.
The current directory isn't related to loading systems.
See [ASDF Manual](https://common-lisp.net/project/asdf/asdf/Configuring-ASDF-to-find-your-systems.html) to get how to configure.

**Comment by duncan-bayne** [comment]
Ah!  Thank you, I'd missed that.  That makes my proposed solution a bad one then; I see you've rejected the PR, which makes sense.

**Comment by duncan-bayne** [comment]
Closing this; PEBKAC on my part :)

**Comment by duncan-bayne** [comment]
(In case anyone else is reading this - I should have been using `~/common-lisp` as my parent directory, which (recent) versions of ASDF searches by default.)
