### ISSUE TITLE
Custom value in aws-sdk:*aws-profile* ignored

### ISSUE THREAD

**Issue by duncan-bayne** [fukamachi/aws-sdk-lisp#4]
I'm trying to specify the profile in my `~/.aws/credentials` file that I'd like to use, but it seems to be ignored in favour of default.

Am I doing this the wrong way, or is this unsupported?

```
CL-USER> (ql:quickload :ironclad)
(:IRONCLAD)
CL-USER> (ql:quickload :aws-sdk)
(:AWS-SDK)
CL-USER> (setq aws-sdk:*aws-profile* "foo")
"foo"
CL-USER> (ql:quickload :aws-sdk/services/s3)
(:AWS-SDK/SERVICES/S3)
Profile 'default' doesn't exist in '~/.aws/credentials'.
   [Condition of type SIMPLE-ERROR]
CL-USER> aws-sdk:*aws-profile*
"foo"
```

The profile definitely exists:

```
[foo]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED
region = ap-southeast-2
```

**Comment by fukamachi** [comment]
Could you try again with `aws-profile` branch?

**Comment by duncan-bayne** [comment]
I have, but it's broken in a slightly different way.

With two profiles in `~/.aws/credentials`:

```
[default]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED

[bayne-family]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED
```
... and two profiles in `~/.aws/config`:

```
[default]

[bayne-family]
```

I get the following error:

```
CL-USER> (ql:quickload :ironclad)
(:IRONCLAD)
CL-USER> (ql:quickload :aws-sdk)
To load "aws-sdk":
  Load 1 ASDF system:
    aws-sdk
; Loading "aws-sdk"
..................................................
[package aws-sdk/credentials/shared]..............
[package aws-sdk/credentials].....................
[package aws-sdk/session].........................
[package aws-sdk/api]

Profile 'default' doesn't exist in '/home/duncan/.aws/config'.
   [Condition of type SIMPLE-ERROR]

Backtrace:
  0: (AWS-SDK/UTILS/CONFIG:READ-FROM-FILE #P"/home/duncan/.aws/config" :PROFILE "default")
  1: (AWS-SDK/SESSION::AWS-REGION)
```

**Comment by fukamachi** [comment]
Thanks for the report.
I added another commit to #5.
It depends on the latest [parser.ini](https://github.com/scymtym/parser.ini) (v0.7).
Could you try it again?

**Comment by fukamachi** [comment]
Hmm, It looks like another issue.
Perhaps, `type` cannot be declared as a type with Clozure CL?
It also causes a compilation error with SBCL.

**Comment by duncan-bayne** [comment]
Would you like me to open a separate issue for this one?

**Comment by fukamachi** [comment]
Oh, would be better for me!

**Comment by duncan-bayne** [comment]
Okay cool.  I'll close this one since https://github.com/fukamachi/aws-sdk-lisp/pull/5 seems to fix it, and open a new one.
